# Generated by Django 3.1.12 on 2024-01-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='voting',
            new_name='votes',
        ),
    ]
